name: Test branch on PR
on:
  pull_request:
    branches:
      - master
jobs:
  check_changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'

  testlint:
    name: Test and Lint
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.changes == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
